name: Build Stok Pintar AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Build App Bundle (.aab)
        run: ./gradlew bundleRelease

      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v3
        with:
          name: stokpintar-aab
          path: app/build/outputs/bundle/release/app-release.aab
